name: vihaan_new
description: Hackathon organized by IEEE-DTU.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  hovering: ^1.0.2
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1
  simple_animations: ^2.4.2
  scroll_to_index: ^2.0.0
  expansion_tile_card: ^2.0.0
  animated_text_kit: ^4.0.0
  timelines: ^0.0.2+1
  url_launcher: ^6.0.2
  universal_html: ^1.2.4
  flutter_conditional_rendering: ^2.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
      - images/


  fonts:
    - family: VihaanIcons
      fonts:
        - asset: fonts/VihaanIcons.ttf
    - family: NunitoSans
      fonts:
        - asset: fonts/NunitoSans-Regular.ttf
        - asset: fonts/NunitoSans-Bold.ttf
          weight: 700
    - family: LeagueSpartan
      fonts:
        - asset: fonts/LeagueSpartan-Bold.otf
          weight: 500
    - family: Helvetica
      fonts:
        - asset: fonts/Helvetica.ttf
